### ISSUE TITLE
BUG: ValueError: 'AnonymousUser' value must be a positive integer or a valid Hashids string.

### ISSUE THREAD

**Issue by sreekanthreddybalne** [djangoflow/django-df-chat#13]
Trying to connect without providing a token results in an error "ValueError: 'AnonymousUser' value must be a positive integer or a valid Hashids string."

I think, we should return a permission denied message via the websocket and gracefully disconnect the user.

**Comment by dokterbob** [comment]
I was unable to replicate this. Do you still get the same error on `main`? If so... how?

Please see the PR as well.
