### ISSUE TITLE
Refactor WebSocket Implementation for Chat Rooms

### ISSUE THREAD

**Issue by eugapx** [djangoflow/django-df-chat#2]
- Modify the WebSocket URL pattern to handle all chat rooms with a single WebSocket URL.
- Update the WebSocket consumer to manage multiple rooms using the new URL pattern.
- Ensure that the chat functionality continues to work correctly after the refactoring.

**Comment by danilredko** [comment]
@eugapx can I get more details about what it means to "Modify the WebSocket URL pattern to handle all chat rooms with a single WebSocket URL"? Currently, it has a format of http://localhost:8000/chat/room_id/, how do we want to make it look like? 
Thanks!

**Comment by eugapx** [comment]
@danilredko  We need to have just http://localhost:8000/ws/chat/. 

This route should send messages from all rooms to the User. The idea is that client shouldn't reconnect to the server when User change his room.

Also, we need to create `UserChat` model with `user = models.OneToOneField(User)` and move `is_online` field from `UserRoom` to `UserChat` model. Because in this case User will connect to all rooms at once, not to the specified only.
